language: csharp
solution: FastCGI.sln
addons:
  apt:
    packages:
    - nginx
install:
  - nuget restore FastCGI.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.5" /p:ToolsVersion="4.0" FastCGI.sln
  - cd ./FastCGI.Tests/bin/Release/
  - mono ../../../testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./FastCGI.Tests.dll
  - mono ../../../testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe --test="FastCGI.Tests.Nginx.Nginx_SingleRequest" ./FastCGI.Tests.dll
  - mono ../../../testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe --test="FastCGI.Tests.Nginx.Nginx_ManyRequests" ./FastCGI.Tests.dll
  - mono ../../../testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe --test="FastCGI.Tests.Nginx.Nginx_ManyRequests_Keepalive" ./FastCGI.Tests.dll
  
