language: csharp
solution: FastCGI.sln
addons:
  apt:
    packages:
    - nginx
install:
  - nuget restore FastCGI.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.5" /p:ToolsVersion="4.0" FastCGI.sln
  - mono ./testrunner/NUnit.Runners.3.7.0/tools/nunit-console.exe ./FastCGI.Tests/bin/Release/FastCGI.Tests.dll
